#!/usr/bin/env node

'use strict';

let childProcess = require('child_process');

let result = childProcess.spawnSync('npm', ['shrinkwrap', '--dev'], {stdio: 'inherit'});
if (result.status !== 0) process.exit(result.status);

result = childProcess.spawnSync(
    process.execPath, ['./tools/npm/clean-shrinkwrap.js'], {stdio: 'inherit'});
if (result.status !== 0) process.exit(result.status);


result = childProcess.spawnSync(
    process.execPath, ['./tools/npm/copy-npm-shrinkwrap'], {stdio: 'inherit'});
if (result.status !== 0) process.exit(result.status);

result = childProcess.spawnSync(
    process.execPath,
    ['./build_defs/node_modules_indexer.js', '.', 'build_defs/node_modules_index.bzl'],
    {stdio: 'inherit'});
if (result.status !== 0) process.exit(result.status);
console.log('updated build_defs/node_modules_index.bzl');
