# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
minimumReleaseAge: 1440
# List of packages to exclude from the minimum release age check.
minimumReleaseAgeExclude:
  - '@angular-devkit/*'
  - '@angular/*'
  - '@ngtools/webpack'
  - '@schematics/*'
  - 'ng-packagr'
  - 'zone.js'
# TODO: Investigate why without minimumReleaseAgeStrict: false it fails with such errors:
# [ERR_PNPM_MISSING_TIME] The metadata of @babel/helper-globals is missing the "time" field
# This error happened while installing the dependencies of @angular-devkit/build-angular@22.0.0-next.7
#  at @babel/preset-env@7.29.2
#  at @babel/plugin-transform-classes@7.28.6
minimumReleaseAgeStrict: false
