load("//devtools/tools:defaults.bzl", "ts_project", "ts_test_library", "zoneless_web_test_suite")

package(default_visibility = ["//devtools:__subpackages__"])

ts_project(
    name = "config",
    srcs = [
        "config.ts",
    ],
    deps = [
        "//devtools/projects/protocol",
    ],
)

ts_test_library(
    name = "test_lib",
    srcs = [
        "config.spec.ts",
    ],
    deps = [
        ":config",
    ],
)

zoneless_web_test_suite(
    name = "test",
    deps = [
        ":test_lib",
    ],
)
