#!/usr/bin/env bash

set -u -e -o pipefail

# Use for BETA and RC releases
# Query Bazel for npm_package and ng_package rules with tags=["release-with-framework"]
# Publish them to npm (tagged next)
for p in $(bazel query --output=label 'attr("tags", "\[.*release-with-framework.*\]", //...) intersect kind(".*_package", //...) except //dist/...'); do
  bazel run -- $p.publish --access public --tag next
done

# TODO(alexeagle): publish everything from bazel and remove this
(cd dist/packages-dist; for p in language-service; do npm publish --access public --tag next $p; done)
