// BannerComponent as initially generated by the CLI
// #docregion
import { Component } from '@angular/core';

@Component({
  selector: 'app-banner',
  template: `<p>banner works!</p>`,
  styles: []
})
export class BannerComponent { }
