/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.dev/license
 */

/* Auto-generated from ng-analyze/index.d.ts via scripts/generate-types.js — do not edit manually. */

export type FileId = number;

/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Standalone iterator produced by `Analyzer::analyze()` for streaming results. */
export declare class AnalysisIterator {
  next(): Promise<CompilationChunk | null>;
}

export declare class Analyzer {
  constructor(options: AnalyzerOptions);
  getTsFileForTemplate(templatePath: string): Array<TemplateUsage> | null;
  updateFileContent(updates: Array<FileUpdate>): Array<string>;
  invalidateFiles(updates: Array<FileInvalidation>): Array<string>;
  analyze(): AnalysisIterator;
  analyzeOptimized(): AnalysisIterator;
  analyzeDelta(): AnalysisIterator;
  analyzeOptimizedDelta(): AnalysisIterator;
  getMetadataForFile(filePath: string): AnalysisResult | null;
  getFileContent(filePath: string): string;
}

/** Test analyzer that uses virtual filesystem for in-memory testing */
export declare class TestAnalyzer {
  constructor(options: TestAnalyzerOptions);
  getMetadataForFile(filePath: string): AnalysisResult | null;
  getFileContent(filePath: string): string;
  getTsFileForTemplate(templatePath: string): Array<TemplateUsage> | null;
  updateFileContent(updates: Array<FileUpdate>): Array<string>;
  invalidateFiles(updates: Array<FileInvalidation>): Array<string>;
  analyze(): AnalysisIterator;
  analyzeOptimized(): AnalysisIterator;
  analyzeDelta(): AnalysisIterator;
  analyzeOptimizedDelta(): AnalysisIterator;
}

export interface AnalysisResult {
  fileId: FileId;
  filePath: string;
  importsEnd: number;
  classes: Array<ClassMetadata>;
  /**
   * The file's static `import` declarations, in source order, so consumers never have to
   * re-parse the source to find or edit an import.
   */
  imports: Array<ImportDeclarationMetadata>;
  typeOnlyExports: Array<string>;
  diagnostics: Array<NgDiagnostic>;
  signalDebugNames: Array<SignalDebugNameMetadata>;
}

export interface AnalyzerOptions {
  tsconfigPath: string;
  optimize?: boolean;
  virtualFiles?: Record<string, string>;
  nodeModulesPathOverride?: string;
  /**
   * Optional allowlist of absolute JS/TS source paths that may be read from disk (used to
   * enforce build boundaries by falling back to `.d.ts` files). Both symlink and resolved paths
   * are permitted.
   */
  allowedSources?: Array<string>;
  /** Workspace name used by `PrefixImportStrategy` for module specifiers (e.g., "google3"). */
  workspaceName?: string;
  /** Root directories used by `PrefixImportStrategy` to strip prefixes. */
  rootDirs?: Array<string>;
}

export interface AngularFieldMetadata {
  kind: string;
  input?: InputMetadata;
  output?: OutputMetadata;
  query?: QueryMetadata;
  coercion?: string;
}

export interface ClassMetadata {
  symbolId: number;
  span: SpanMetadata;
  decoratedSpan: SpanMetadata;
  nameSpan?: SpanMetadata;
  className?: string;
  ref?: ReferenceMetadata;
  constructorParams?: Array<ConstructorParamMetadata>;
  memberDecorators?: Array<DecoratedMemberMetadata>;
  laterDeclarationReferences: Array<SpanMetadata>;
  injectable?: InjectableMetadata;
  service?: ServiceMetadata;
  component?: ComponentMetadata;
  directive?: DirectiveMetadata;
  pipe?: PipeMetadata;
  ngModule?: NgModuleMetadata;
  fields: Array<AngularFieldMetadata>;
  flattenedFields?: Array<AngularFieldMetadata>;
  /**
   * Member API surface pre-derived from `fields`: `model()` members are expanded into a
   * signal input plus a `<name>Change` output, and inputs matched by an
   * `ngAcceptInputType_` coercion member are marked coerced. Query lists are sorted
   * signal-first, then `first`, then the rest (stable). `fields` stays on the wire for
   * consumers that need the raw per-member view (TCB adapter, indexer).
   */
  inputs: Array<InputMetadata>;
  outputs: Array<OutputMetadata>;
  queries: Array<QueryMetadata>;
  viewQueries: Array<QueryMetadata>;
  /**
   * Every span the preprocessor must delete for this class: the class's Angular decorators
   * plus each member-level `@Input`/`@Output`/query/`@HostBinding`/`@HostListener`
   * decorator.
   */
  removalSpans: Array<SpanMetadata>;
  /**
   * Edits adding the `@nocollapse` tsickle would have put on static properties had the
   * class decorators not been stripped. Apply only when annotating for Closure Compiler.
   */
  nocollapseInsertions: Array<TextInsertionMetadata>;
  /**
   * The ready-to-splice `declare static ngAcceptInputType_...` member block for
   * decorator-based inputs with a `transform`, empty when there are none.
   */
  coercionMembers: string;
  hostBindings: Array<HostBindingMetadata>;
  hostListeners: Array<HostListenerMetadata>;
  typeParameters?: Array<TypeParameterMetadata>;
  hasNgTemplateContextGuard: boolean;
  ngTemplateGuards: Array<TemplateGuardMetadata>;
  hasNgFieldDirective: boolean;
  superClass?: DeclarationTuple;
  usesInheritance: boolean;
  usesOnChanges: boolean;
  isExported: boolean;
  hasNonExportedBounds: boolean;
}

export interface CompilationChunk {
  files: Array<AnalysisResult>;
  staticEdges?: Record<string, Array<FileId>>;
}

export interface ComponentMetadata {
  decoratorName?: string;
  selector?: string;
  imports?: Array<ReferenceMetadata>;
  template?: string;
  /**
   * Span of an inline string/template literal's content (excluding delimiters; `getTemplateRange`
   * for `sourceMapping.type === 'direct'`). `None` for external or indirectly computed templates.
   */
  templateContentSpan?: SpanMetadata;
  /** Span of the inline `template` expression (used to anchor template diagnostics). */
  templateSpan?: SpanMetadata;
  /** True when an inline `template` is present but not statically resolvable. */
  templateDynamic: boolean;
  templateUrl?: UrlMetadata;
  styles?: Array<string>;
  stylesFromUrls?: Array<string>;
  styleUrls?: Array<UrlMetadata>;
  standalone: boolean;
  signals: boolean;
  exportAs?: Array<string>;
  schemas?: Array<string>;
  rawImportsSpan?: SpanMetadata;
  /** Preserved `@Component.imports` expression span for local compilation mode. */
  importsFactorySpan?: SpanMetadata;
  resolvedDeclarations?: Array<DeclarationMetadata>;
  /** The component's own `hostDirectives`, resolved in its own frame for the type-check block. */
  resolvedHostDirectives?: Array<ResolvedHostDirectiveMetadata>;
  /**
   * Bare side-effect import specifiers (`import '<specifier>';`) for non-standalone components
   * whose declaring `@NgModule` is in another file (`LocalCompilationExtraImportsTracker`).
   * Already projected into this file's frame by Rust; emit verbatim.
   */
  localCompilationExtraImports?: Array<string>;
  /** Syntax of the `host` object literal, for the type-check block. */
  hostProperties: Array<HostPropertyMetadata>;
  /**
   * The `host` property's value expression span — the node ngtsc anchors host binding
   * parse/verify diagnostics on.
   */
  hostSpan?: SpanMetadata;
  /**
   * The `host` object reduced by the partial evaluator, in source order. `None` when the
   * decorator has no `host` field or it did not evaluate to an object.
   */
  hostMetadata?: Array<HostMetadataEntry>;
  /** Raw hostDirectives expression from the decorator */
  hostDirectives?: Array<HostDirectiveMetadata>;
  providersSpan?: SpanMetadata;
  viewProvidersSpan?: SpanMetadata;
  /**
   * `encapsulation` resolved to its numeric `ViewEncapsulation` value (`None` when absent or
   * unresolved; consumers default to `Emulated`).
   * https://github.com/angular/angular/blob/83622ee/packages/compiler-cli/src/ngtsc/annotations/component/src/handler.ts#L532-L542
   */
  encapsulation?: number;
  /** `changeDetection` expression as written in the decorator, matching ngtsc's local compilation behavior. `None` when absent. */
  changeDetection?: string;
  preserveWhitespaces?: boolean;
  animationsSpan?: SpanMetadata;
  animationTriggerNames?: LegacyAnimationTriggerNames;
  argsSpan?: SpanMetadata;
  preservedDecoratorProperties?: Array<SpanMetadata>;
  declaringNgModule?: DeclaringNgModule;
  foreignImports?: Array<ForeignImportMetadata>;
  isJit: boolean;
  deferredImports?: Array<ReferenceMetadata>;
  deferredImportsByBlock?: Record<string, Array<ReferenceMetadata>>;
  deferredImportsSpan?: SpanMetadata;
  resolvedDeferredDeclarations?: Array<DeclarationMetadata>;
  resolvedDeferredDeclarationsByBlock?: Record<string, Array<DeclarationMetadata>>;
}

export interface ConstructorParamMetadata {
  typeName?: string;
  /**
   * Module specifier the type was imported from, when the type resolves to a (non-aliased)
   * named import (e.g. `@angular/core` for `ElementRef`). `None` for locally declared types.
   * Used so DI tokens that reference an imported symbol are emitted through the matching
   * namespace import (e.g. `i0.ElementRef`), mirroring ngtsc's import manager.
   */
  typeModule?: string;
  isTypeOnly: boolean;
  /**
   * Whether `type_name` was resolved to a declaration that has a runtime value, either in this
   * file or by chasing the import across files. References we could not resolve at all —
   * ambient globals, members of an ambient namespace, specifiers outside the compilation — are
   * emitted optimistically, so the `ɵsetClassMetadata` entry has to be guarded with
   * `@ts-ignore`. This is the inverse of ngtsc's `TypeValueReference#valueUnverified`.
   */
  isValueVerified: boolean;
  decorators: Array<DecoratorMetadata>;
}

export interface DeclarationMetadata {
  name: string;
  ref: ReferenceMetadata;
  /** Reference projected into the declaring NgModule's file for remote scoping (`ɵɵsetComponentScope`). */
  refInDeclaringModule?: ReferenceMetadata;
  nameSpan: SpanMetadata;
  declarationType: string;
  selector?: string;
  pipeName?: string;
  isStandalone?: boolean;
  exportAs?: Array<string>;
  fileId: FileId;
  filePath?: string;
  hostDirectives?: Array<HostDirectiveMetadata>;
  fields?: Array<AngularFieldMetadata>;
  flattenedFields?: Array<AngularFieldMetadata>;
  ngContentSelectors?: Array<string>;
  typeParameters?: Array<TypeParameterMetadata>;
  hasNgTemplateContextGuard: boolean;
  ngTemplateGuards: Array<TemplateGuardMetadata>;
  animationTriggerNames?: LegacyAnimationTriggerNames;
  hasNgFieldDirective: boolean;
  isForwardRef: boolean;
  isStructural: boolean;
  cycleProne?: boolean;
  isExported: boolean;
  hasNonExportedBounds: boolean;
  isExplicitlyDeferred: boolean;
  deferredBlocks?: Array<string>;
  /**
   * Resolved `hostDirectives` in the consuming component's frame; they apply only where this
   * declaration matches and are not members of the consumer's scope.
   */
  resolvedHostDirectives?: Array<ResolvedHostDirectiveMetadata>;
}

export interface DeclarationTuple {
  /** The local binding: `Bar` in `import {Foo as Bar}`. */
  localName: string;
  /**
   * The exported name, when it differs from `local_name`: `Foo` in `import {Foo as Bar}`,
   * `default` for a default import.
   */
  importedName?: string;
  importSource?: string;
}

export interface DeclaringNgModule {
  filePath: string;
  symbolId: number;
}

/**
 * A non-static, non-private class member that carries at least one decorator. Mirrors the
 * per-member entries ngtsc builds for the property-decorator map of `ɵsetClassMetadata`.
 * https://github.com/angular/angular/blob/83622ee/packages/compiler-cli/src/ngtsc/annotations/common/src/metadata.ts#L91-L131
 */
export interface DecoratedMemberMetadata {
  propertyName: string;
  /** Whether the member name must be quoted (the name node is a string literal). */
  isStringLiteral: boolean;
  decorators: Array<DecoratorMetadata>;
}

export interface DecoratorArg {
  value: string;
  isLiteral: boolean;
}

/** A single decorator captured on a class member or constructor parameter for `ɵsetClassMetadata`. */
export interface DecoratorMetadata {
  name: string;
  canonicalName?: string;
  args?: Array<DecoratorArg>;
  decoratorSpan?: SpanMetadata;
  /**
   * Span of the decorator's argument list (first arg start..last arg end), used to emit the
   * `args: [...]` of `ɵsetClassMetadata` verbatim from source. `None` when there are no args.
   */
  argsSpan?: SpanMetadata;
  /**
   * Pre-rendered argument string with type arguments stripped (e.g. for `ChildComponent<T>` -> `ChildComponent`),
   * emitted when generic type arguments are stripped for static block compatibility in `ɵsetClassMetadata`.
   */
  argsString?: string;
  /**
   * Whether the decorator is imported from `@angular/core`. Only Angular decorators are
   * captured in the `ɵsetClassMetadata` constructor-parameter metadata.
   * https://github.com/angular/angular/blob/83622ee/packages/compiler-cli/src/ngtsc/annotations/common/src/metadata.ts#L172-L179
   */
  isAngular: boolean;
}

export interface DependencyMetadata {
  tokenSpan?: SpanMetadata;
  host: boolean;
  optional: boolean;
  self: boolean;
  skipSelf: boolean;
}

export interface DirectiveMetadata {
  decoratorName?: string;
  selector?: string;
  standalone: boolean;
  signals: boolean;
  isStructural: boolean;
  exportAs?: Array<string>;
  /** Syntax of the `host` object literal, for the type-check block. */
  hostProperties: Array<HostPropertyMetadata>;
  /**
   * The `host` property's value expression span — the node ngtsc anchors host binding
   * parse/verify diagnostics on.
   */
  hostSpan?: SpanMetadata;
  /**
   * The `host` object reduced by the partial evaluator, in source order. `None` when the
   * decorator has no `host` field or it did not evaluate to an object.
   */
  hostMetadata?: Array<HostMetadataEntry>;
  /** Raw hostDirectives expression from the decorator */
  hostDirectives?: Array<HostDirectiveMetadata>;
  providersSpan?: SpanMetadata;
  argsSpan?: SpanMetadata;
  declaringNgModule?: DeclaringNgModule;
  isJit: boolean;
}

export enum ExpressionValueKindMetadata {
  String = 'string',
  Identifier = 'identifier',
  Unspecified = 'unspecified',
}

export interface ExpressionValueMetadata {
  kind: ExpressionValueKindMetadata;
  text?: string;
  sourceSpan: SpanMetadata;
}

export interface FileInvalidation {
  filePath: string;
  updateType: FileUpdateType;
}

export interface FileUpdate {
  filePath: string;
  content: string;
}

export enum FileUpdateType {
  Created = 0,
  Deleted = 1,
  Changed = 2,
}

export interface ForeignImportMetadata {
  name: string;
  span: SpanMetadata;
}

export interface HostBindingMetadata {
  memberName: ExpressionValueMetadata;
  arguments: Array<ExpressionValueMetadata>;
  hostPropertyName?: string;
  decoratorSpan: SpanMetadata;
  memberSpan: SpanMetadata;
}

export interface HostDirectiveBinding {
  publicName: string;
  bindingName: string;
}

export interface HostDirectiveMetadata {
  /** Reference to the host directive class in the emitting file's frame. */
  directive: ReferenceMetadata;
  inputs?: Array<HostDirectiveBinding>;
  outputs?: Array<HostDirectiveBinding>;
  isForwardRef: boolean;
}

export interface HostListenerMetadata {
  methodName: ExpressionValueMetadata;
  eventName?: ExpressionValueMetadata;
  resolvedEventName?: string;
  args: Array<ExpressionValueMetadata>;
  runtimeArgs?: Array<string>;
  decoratorSpan: SpanMetadata;
  memberSpan: SpanMetadata;
}

/**
 * One entry of the `host` object reduced by the partial evaluator (`Record<string, string | Expression>`).
 * https://github.com/angular/angular/blob/e3ac727/packages/compiler-cli/src/ngtsc/annotations/directive/src/shared.ts#L2021-L2047
 */
export interface HostMetadataEntry {
  key: string;
  /**
   * The string the evaluator folded this entry to. Exactly one of `value` and `expression`
   * is set.
   */
  value?: string;
  /** Source text of a value that is not statically evaluable, for verbatim re-emission. */
  expression?: string;
}

export interface HostPropertyMetadata {
  key: ExpressionValueMetadata;
  value: ExpressionValueMetadata;
}

/** How to write an import for a symbol, if the consumer decides it needs one. */
export interface ImportableRef {
  /** Module specifier to import from. */
  specifier: string;
  /** Exported symbol name on `specifier`. */
  symbol: string;
}

/** One binding introduced by a static `import` declaration. */
export interface ImportBindingMetadata {
  /** Source span of the individual specifier (`Foo`, `Foo as Bar`, `type Foo`, or `* as ns`). */
  span: SpanMetadata;
  /** Identifier bound in the importing file. */
  local: string;
  /** Exported symbol name (`"default"` for default imports, `None` for namespace imports). */
  imported?: string;
  /** True when `local` is referenced outside stripped decorator metadata (`@Component.imports`). */
  eagerlyReferenced: boolean;
  /**
   * True when `local` has a surviving value-position reference; ngtsc decides `@defer`
   * eligibility on this. `eagerly_referenced` then decides whether a deferrable import is
   * deleted outright or has its non-type specifiers converted to `type`.
   */
  valueReferenced: boolean;
  /** True for `import type { X }` / `import { type X }` (ignored by ngtsc's deferrability check). */
  isType: boolean;
}

/**
 * Static `import` declaration metadata used for `@defer` import pruning; deferral is
 * all-or-nothing per declaration (`DeferredSymbolTracker`).
 */
export interface ImportDeclarationMetadata {
  /** Statement span for diagnostic anchoring. */
  span: SpanMetadata;
  /**
   * `span` extended over any trailing line terminator for clean removal (diagnostics use `span`
   * so the squiggle stays on one line).
   */
  removalSpan: SpanMetadata;
  /** Raw module specifier. */
  specifier: string;
  /** Introduced bindings (empty for bare side-effect imports). */
  bindings: Array<ImportBindingMetadata>;
}

export interface ImportViaMetadata {
  moduleSpecifier: string;
  symbol?: string;
}

export interface InjectableMetadata {
  decoratorName?: string;
  providedIn?: ProviderField;
  useClass?: ProviderField;
  useExisting?: ProviderField;
  useFactory?: ProviderField;
  useValue?: ProviderField;
  argsSpan?: SpanMetadata;
  deps?: Array<DependencyMetadata>;
}

export interface InputMetadata {
  name: string;
  alias?: string;
  required: boolean;
  isSignal: boolean;
  decoratorSpan?: SpanMetadata;
  propertySpan?: SpanMetadata;
  transform?: TransformMetadata;
  isRestricted: boolean;
  isLiteral: boolean;
  isCoerced: boolean;
}

export enum IsolatedTypeElementKind {
  /**
   * `typeof <span|refs>`: an entity-name expression (`Foo`, `ns.Foo`), optionally
   * pre-evaluated to one or more references when it aliases a local const.
   */
  Typeof = 'typeof',
  /**
   * `ReturnType<typeof <span>>`: a call expression whose callee is an entity name
   * (`StoreModule.forFeature(...)`, `fn()`), where `span` covers the callee.
   */
  CallReturnType = 'callReturnType',
  /**
   * `[typeof A, typeof B, ...]`: an element that locally evaluates to an array of
   * references.
   */
  ReferenceTuple = 'referenceTuple',
  /** `never`: an expression that cannot be represented with `typeof`. */
  Never = 'never',
}

export interface IsolatedTypeElementMetadata {
  kind: IsolatedTypeElementKind;
  /**
   * Source span to slice: the unwrapped entity name for `Typeof`, the callee entity name
   * for `CallReturnType`, or the offending expression for `Never` diagnostics.
   */
  span?: SpanMetadata;
  /**
   * Resolved references when the element was folded through the partial evaluator (a single
   * reference for `Typeof`, or the full list for `ReferenceTuple`).
   */
  references?: Array<ReferenceMetadata>;
}

export interface IsolatedTypeTupleMetadata {
  /**
   * True when the decorator slot was written as an array literal (`imports: [...]`), so the
   * emitter wraps `elements` in a tuple `[...]`; false when the whole slot is a single
   * non-array expression (`imports: MY_IMPORTS`), emitted bare as `typeof MY_IMPORTS`.
   */
  isArrayLiteral: boolean;
  elements: Array<IsolatedTypeElementMetadata>;
}

export interface LegacyAnimationTriggerNames {
  staticTriggerNames: Array<string>;
  includesDynamicAnimations: boolean;
}

export interface NgDiagnostic {
  category: number;
  code: number;
  messageText: string;
  filePath?: string;
  span?: SpanMetadata;
}

export interface NgModuleMetadata {
  decoratorName?: string;
  /**
   * True when any declaration or import came from a `forwardRef`-like foreign resolver, so
   * remote-scope arrays must be wrapped in a closure.
   * https://github.com/angular/angular/blob/c1829f6/packages/compiler-cli/src/ngtsc/annotations/ng_module/src/handler.ts#L719-L720
   */
  remoteScopesMayRequireCycleProtection: boolean;
  declarations?: Array<ReferenceMetadata>;
  /**
   * Subset of `declarations` also listed in `exports`, in declaration order (`exportedDeclarations`
   * for `onlyPublishPublicTypingsForNgModules`).
   */
  publicDeclarations?: Array<ReferenceMetadata>;
  imports?: Array<ReferenceMetadata>;
  injectorImports?: Array<ReferenceMetadata>;
  exports?: Array<ReferenceMetadata>;
  bootstrap?: Array<ReferenceMetadata>;
  /**
   * `imports` elements to re-emit verbatim into `ɵinj.imports` because they contain a
   * `ModuleWithProviders` call. `index` is the position in the final list, interleaved
   * with the resolved injector imports.
   */
  injectorImportRawSpans?: Array<RawInjectorImportMetadata>;
  providersSpan?: SpanMetadata;
  idSpan?: SpanMetadata;
  schemas?: Array<string>;
  argsSpan?: SpanMetadata;
  /**
   * Raw source spans of the `declarations`/`imports`/`exports`/`bootstrap` value
   * expressions, emitted verbatim in LOCAL compilation mode's `ɵɵsetNgModuleScope`.
   */
  declarationsSpan?: SpanMetadata;
  importsSpan?: SpanMetadata;
  exportsSpan?: SpanMetadata;
  bootstrapSpan?: SpanMetadata;
  /**
   * Raw source spans of the top-level `imports`/`exports` array elements, emitted
   * verbatim (concatenated) in LOCAL compilation mode's `ɵinj.imports`.
   */
  localImportsElementSpans?: Array<SpanMetadata>;
  localExportsElementSpans?: Array<SpanMetadata>;
  /**
   * Syntactic type-tuple representation of `imports` for `emitDeclarationOnly`
   * (`R3NgModuleMetadataKind.Isolated`), mirroring `transformToTypeTupleExpression` in
   * `ngtsc/annotations/ng_module/src/handler.ts`. `None` when the slot is absent or an
   * empty array literal (both emit `never`).
   */
  isolatedImports?: IsolatedTypeTupleMetadata;
  /** Syntactic type-tuple representation of `exports` for `emitDeclarationOnly`. */
  isolatedExports?: IsolatedTypeTupleMetadata;
}

export interface OutputMetadata {
  name: string;
  alias?: string;
  decoratorSpan?: SpanMetadata;
  propertySpan?: SpanMetadata;
  isSignal: boolean;
}

export interface PipeMetadata {
  decoratorName?: string;
  name: string;
  pure?: boolean;
  standalone?: boolean;
  argsSpan?: SpanMetadata;
  declaringNgModule?: DeclaringNgModule;
}

export interface ProviderField {
  span: SpanMetadata;
  isForwardRef: boolean;
}

export interface QueryMetadata {
  propertyName: string;
  first: boolean;
  isForwardRef: boolean;
  /**
   * Predicate expression with `forwardRef` stripped (emitted verbatim when `predicate_selectors`
   * is `None`, and used for signal query class metadata).
   */
  predicateSpan: SpanMetadata;
  /** Selector strings when the predicate evaluated to `string[]` (unsplit on commas). */
  predicateSelectors?: Array<string>;
  descendants: boolean;
  emitDistinctChangesOnly: boolean;
  readSpan?: SpanMetadata;
  isStatic: boolean;
  isSignal: boolean;
  decoratorSpan?: SpanMetadata;
  isView: boolean;
  propertySpan?: SpanMetadata;
}

export interface RawInjectorImportMetadata {
  index: number;
  span: SpanMetadata;
}

/**
 * How a consuming file can refer to a symbol. Encodes how to reference the target both in-situ
 * (within the consumer file) and for type-checking (`.ngtypecheck.ts`).
 *
 * Fields are independent, not alternatives: a cross-file symbol the consumer already imports has
 * both `local_alias` and an import. Callers pick per use: expressions prefer the local binding,
 * while emits that need a specifier (e.g. extra side-effect imports) read `consumer_import`.
 */
export interface ReferenceMetadata {
  /** How to import the target into the consumer file (in-situ), if not bound locally. */
  consumerImport?: ImportableRef;
  /** How to import the target into an external type-checking file (.ngtypecheck.ts). */
  typecheckImport?: ImportableRef;
  /** Identifier in the consumer file's lexical scope (for same-file declarations or local aliases). */
  localAlias?: string;
}

/** Wire form of `ResolvedHostDirective`. */
export interface ResolvedHostDirectiveMetadata {
  directive: DeclarationMetadata;
  inputs?: Array<HostDirectiveBinding>;
  outputs?: Array<HostDirectiveBinding>;
}

export interface ServiceMetadata {
  decoratorName?: string;
  autoProvided?: boolean;
  factory?: ProviderField;
  argsSpan?: SpanMetadata;
}

/**
 * Implicit signal `debugName` insertion (`signalMetadataTransform`).
 * https://github.com/angular/angular/blob/5b525f9/packages/compiler-cli/src/ngtsc/transform/src/implicit_signal_debug_name_transform.ts#L11-L93
 */
export interface SignalDebugNameMetadata {
  /** UTF-16 insertion offset (after `{` when spreading into options, or at the end of the call's arguments). */
  position: number;
  /** Unescaped variable or property name. */
  debugName: string;
  /** Spread `debugName` into the existing options object literal instead of appending an argument. */
  intoOptions: boolean;
  /** Whether a `, ` separator is needed (after when spreading into non-empty options, before when appending). */
  needsSeparator: boolean;
  /** Prepend `undefined, ` when appending options to a zero-argument call whose first parameter is the initial value. */
  prependUndefined: boolean;
}

export interface SpanMetadata {
  start: number;
  end: number;
}

export interface TemplateGuardMetadata {
  inputName: string;
  type: string;
}

export interface TemplateUsage {
  tsFilePath: string;
  symbolId: number;
}

/** Options for creating a test analyzer */
export interface TestAnalyzerOptions {
  /** Virtual files to use for analysis */
  virtualFiles: Record<string, string>;
  /** Whether to use optimized two-pass mode */
  optimize?: boolean;
  /** Path to tsconfig.json (must be a virtual file path) */
  tsconfigPath: string;
  /** Path to real node_modules for resolving @angular packages */
  nodeModulesPathOverride?: string;
  /** Workspace name used by `PrefixImportStrategy` (e.g. "google3") */
  workspaceName?: string;
  /** Root directories for `PrefixImportStrategy` */
  rootDirs?: Array<string>;
}

/** Text to splice into the source at `position`, a UTF-16 offset. */
export interface TextInsertionMetadata {
  position: number;
  text: string;
}

export interface TransformMetadata {
  kind: string;
  span: SpanMetadata;
  typeSpan?: SpanMetadata;
}

export interface TypeParameterMetadata {
  name: string;
  representation: string;
  representationWithDefault: string;
  hasDefault: boolean;
  typeRefs?: Array<TypeRefMetadata>;
}

export interface TypeRefMetadata {
  name: string;
  moduleSpecifier: string;
  symbol: string;
  span?: SpanMetadata;
}

/**
 * URL resource (template or stylesheet) referenced in a component decorator, with its resolved
 * path and literal span (used for Kythe cross-references).
 */
export interface UrlMetadata {
  url: string;
  resolvedPath: string;
  stringLiteralSpan?: SpanMetadata;
}
