import * as i1 from "path/to/my/file.jpg" with { loader: "image-file" };
…
MyApp.ɵfac = function MyApp_Factory(t) { return new (t || MyApp)(); };
MyApp.ɵcmp = /*@__PURE__*/ $r3$.ɵɵdefineComponent({
  …
  consts: [["width", i1.width, "height", i1.height, "ngLocalSrc", i1.default, "test", "baz", 1, "foobar"]],
  template: function MyApp_Template(rf, ctx) {
    …
  },
  …
});
…
$r3$.ɵsetClassMetadata(MyApp, …);
