#!/usr/bin/env ts-node
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */

// Loads the ng-dev cli, automatically executing it.
require('./cli.ts');
