
// THIS FILE IS AUTOMATICALLY GENERATED. TO UPDATE THIS FILE YOU NEED TO CHANGE
// THE CORRESPONDING JSON SCHEMA FILE. See README.md.

// tslint:disable:no-global-tslint-disable
// tslint:disable

export interface Schema {
  /**
   * The name of the project.
   */
  name: string;
}
