
// THIS FILE IS AUTOMATICALLY GENERATED. TO UPDATE THIS FILE YOU NEED TO CHANGE THE
// CORRESPONDING JSON SCHEMA FILE, THEN RUN devkit-admin build (or bazel build ...).

// tslint:disable:no-global-tslint-disable
// tslint:disable

export interface Schema {
  /**
   * The name of the project.
   */
  name?: string;
  /**
   * When true, does not install dependency packages.
   */
  skipInstall?: boolean;
}
