load("//devtools/tools:defaults.bzl", "copy_to_bin", "js_library")

package(default_visibility = ["//visibility:public"])

copy_to_bin(
    name = "js_lib_files",
    srcs = [
        "esbuild-plugin.d.ts",
        "esbuild-plugin.mjs",
    ],
)

js_library(
    name = "js_lib",
    srcs = [":js_lib_files"],
    deps = [
        "//:node_modules/@angular/build",
    ],
)
