  # Set up env variables for testing
  export AIO_NGINX_HOSTNAME=$TEST_AIO_NGINX_HOSTNAME
  export AIO_NGINX_PORT_HTTP=$TEST_AIO_NGINX_PORT_HTTP
  export AIO_NGINX_PORT_HTTPS=$TEST_AIO_NGINX_PORT_HTTPS

  export AIO_ARTIFACT_PATH=$TEST_AIO_ARTIFACT_PATH
  export AIO_BUILDS_DIR=$TEST_AIO_BUILDS_DIR
  export AIO_DOMAIN_NAME=$TEST_AIO_DOMAIN_NAME
  export AIO_GITHUB_ORGANIZATION=$TEST_AIO_GITHUB_ORGANIZATION
  export AIO_GITHUB_REPO=$TEST_AIO_GITHUB_REPO
  export AIO_GITHUB_TEAM_SLUGS=$TEST_AIO_GITHUB_TEAM_SLUGS
  export AIO_SIGNIFICANT_FILES_PATTERN=$TEST_AIO_SIGNIFICANT_FILES_PATTERN
  export AIO_TRUSTED_PR_LABEL=$TEST_AIO_TRUSTED_PR_LABEL
  export AIO_PREVIEW_SERVER_HOSTNAME=$TEST_AIO_PREVIEW_SERVER_HOSTNAME
  export AIO_PREVIEW_SERVER_PORT=$TEST_AIO_PREVIEW_SERVER_PORT
  export AIO_ARTIFACT_MAX_SIZE=$TEST_AIO_ARTIFACT_MAX_SIZE

  export AIO_CIRCLE_CI_TOKEN=TEST_CIRCLE_CI_TOKEN
  export AIO_GITHUB_TOKEN=TEST_GITHUB_TOKEN
