/**
 * @license
 * Copyright Google LLC All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */

export const VE_PRIVATE_REEXPORT_PREFIX = '\u0275ngve$';

/**
 * Exports that have been generated by the View Engine compiler are not considered by the Ivy
 * compiler as their names may change between versions, making them unsuitable for Ivy's partial
 * compilation mode. In partial compilation, the generated partial declarations have to refer to a
 * library declarations using their stable export name.
 */
export function shouldExcludeExport(exportName: string): boolean {
  return exportName.startsWith(VE_PRIVATE_REEXPORT_PREFIX);
}
