consts: [["foo", "1", "bar", "2"], ["empty-foo", "1", "empty-bar", "2"]]
…
$r3$.ɵɵrepeaterCreate(0, MyApp_For_1_Template, 2, 1, "div", 0, i0.ɵɵrepeaterTrackByIdentity, false, MyApp_ForEmpty_2_Template, 2, 0, "span", 1);