exports_files([
    "nodejs_launcher_template.sh",
    "jasmine_launcher_template.sh",
    "karma_launcher_template.sh",
    "rollup_config_template.js",
    "protractor_launcher_template.sh",
    "ts_api_guardian_launcher_template.sh",
])
