load("//adev/shared-docs:defaults.bzl", "copy_to_bin")
load("//tools:defaults.bzl", "ng_project", "zoneless_web_test_suite")

# All example files.
filegroup(
    name = "examples",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

# Example files that can be embedded as preview components.
copy_to_bin(
    name = "embeddable",
    srcs = glob(
        ["**/app/**"],
        exclude = [
            "i18n/**",  # @angular/localize/init not available in docs app
            "elements/**",  # @angular/elements not available in docs app
            "service-worker-getting-started/**",  # @angular/service-worker not available in docs app
            # TODO: The following examples have broken code that does not compile, fix them and remove them from this list.
            "reactive-forms/**",
            "form-validation/**",
        ],
    ),
    visibility = ["//visibility:public"],
)

ng_project(
    name = "reactive_forms_profile_editor_test_lib",
    testonly = True,
    srcs = [
        "reactive-forms/src/app/profile-editor/address-editor/address-editor.component.ts",
        "reactive-forms/src/app/profile-editor/profile-editor.component.spec.ts",
        "reactive-forms/src/app/profile-editor/profile-editor.component.ts",
    ],
    assets = [
        "reactive-forms/src/app/profile-editor/address-editor/address-editor.component.css",
        "reactive-forms/src/app/profile-editor/address-editor/address-editor.component.html",
        "reactive-forms/src/app/profile-editor/profile-editor.component.css",
        "reactive-forms/src/app/profile-editor/profile-editor.component.html",
    ],
    tsconfig = "//packages:tsconfig_test",
    deps = [
        "//packages/common",
        "//packages/core",
        "//packages/core/testing",
        "//packages/forms",
    ],
)

zoneless_web_test_suite(
    name = "reactive_forms_profile_editor_test",
    deps = [":reactive_forms_profile_editor_test_lib"],
)
