// #docregion
// Reduced version of the initial AppComponent generated by CLI
import { Component } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-root',
  template: '<h1>Welcome to {{title}}!</h1>',
})
export class AppComponent {
  title = 'app';
}
