export const script = `
'use strict';function $jscomp$arrayIteratorImpl(array){var index=0;return function(){return index<array.length?{done:!1,value:array[index++]}:{done:!0}}};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var goog$global=this||self;/*

 Copyright 2013 Google LLC.
 SPDX-License-Identifier: Apache-2.0
*/
var module$contents$google3$javascript$jsaction$cache_parseCache={};var module$contents$google3$javascript$jsaction$event_isMac="undefined"!==typeof navigator&&/Macintosh/.test(navigator.userAgent),module$exports$google3$javascript$jsaction$event$isGecko="undefined"!==typeof navigator&&!/Opera|WebKit/.test(navigator.userAgent)&&/Gecko/.test(navigator.product);var module$contents$google3$javascript$jsaction$event_contract_container_isIos="undefined"!==typeof navigator&&/iPhone|iPad|iPod/.test(navigator.userAgent);function module$exports$google3$javascript$jsaction$event_contract_container$EventContractContainer(element){this.JSC$2220_element=element;this.handlerInfos=[]}
module$exports$google3$javascript$jsaction$event_contract_container$EventContractContainer.prototype.addEventListener=function(eventType,getHandler){module$contents$google3$javascript$jsaction$event_contract_container_isIos&&(this.JSC$2220_element.style.cursor="pointer");var JSCompiler_temp_const=this.handlerInfos,JSCompiler_temp_const$jscomp$0=JSCompiler_temp_const.push,element=this.JSC$2220_element;getHandler=getHandler(this.JSC$2220_element);var capture=!1;if("focus"===eventType||"blur"===eventType||
"error"===eventType||"load"===eventType||"toggle"===eventType)capture=!0;element.addEventListener(eventType,getHandler,capture);JSCompiler_temp_const$jscomp$0.call(JSCompiler_temp_const,{eventType:eventType,handler:getHandler,capture:capture})};function module$exports$google3$javascript$jsaction$event_contract_multi_container$EventContractMultiContainer(){this.containers=[];this.eventHandlerInstallers=[]}module$exports$google3$javascript$jsaction$event_contract_multi_container$EventContractMultiContainer.prototype.addEventListener=function(eventType,getHandler){function eventHandlerInstaller(container){container.addEventListener(eventType,getHandler)}for(var i=0;i<this.containers.length;i++)eventHandlerInstaller(this.containers[i]);this.eventHandlerInstallers.push(eventHandlerInstaller)};var module$contents$google3$javascript$jsaction$eventcontract_EMPTY_ACTION_MAP={},module$contents$google3$javascript$jsaction$eventcontract_REGEXP_SEMICOLON=/\s*;\s*/;
function module$exports$google3$javascript$jsaction$eventcontract$EventContract(){var containerManager;this.containerManager=containerManager=void 0===containerManager?new module$exports$google3$javascript$jsaction$event_contract_multi_container$EventContractMultiContainer:containerManager;this.eventHandlers={};this.browserEventTypeToExtraEventTypes={};this.dispatcher=null;this.queuedEventInfos=[]}
module$exports$google3$javascript$jsaction$eventcontract$EventContract.prototype.handleEvent=function(eventType,event,container){JSCompiler_StaticMethods_handleEventInfo(this,{eventType:eventType,event:event,targetElement:event.target,eic:container,action:"",actionElement:null,timeStamp:Date.now(),eirp:void 0,eiack:void 0})};
function JSCompiler_StaticMethods_handleEventInfo(JSCompiler_StaticMethods_handleEventInfo$self,eventInfo$jscomp$0,allowRehandling){allowRehandling=void 0===allowRehandling?!0:allowRehandling;if(!JSCompiler_StaticMethods_handleEventInfo$self.dispatcher){eventInfo$jscomp$0.eirp=!0;var $jscomp$optchain$tmp1103933637$0;null==($jscomp$optchain$tmp1103933637$0=JSCompiler_StaticMethods_handleEventInfo$self.queuedEventInfos)||$jscomp$optchain$tmp1103933637$0.push(eventInfo$jscomp$0)}if($jscomp$optchain$tmp1103933637$0=
"click"===eventInfo$jscomp$0.eventType)$jscomp$optchain$tmp1103933637$0=eventInfo$jscomp$0.event,$jscomp$optchain$tmp1103933637$0=module$contents$google3$javascript$jsaction$event_isMac&&$jscomp$optchain$tmp1103933637$0.metaKey||!module$contents$google3$javascript$jsaction$event_isMac&&$jscomp$optchain$tmp1103933637$0.ctrlKey||2===$jscomp$optchain$tmp1103933637$0.which||null==$jscomp$optchain$tmp1103933637$0.which&&4===$jscomp$optchain$tmp1103933637$0.button||$jscomp$optchain$tmp1103933637$0.shiftKey;
$jscomp$optchain$tmp1103933637$0&&(eventInfo$jscomp$0.eventType="clickmod");for($jscomp$optchain$tmp1103933637$0=eventInfo$jscomp$0.targetElement;$jscomp$optchain$tmp1103933637$0&&$jscomp$optchain$tmp1103933637$0!==eventInfo$jscomp$0.eic;){var type=void 0,actionElement=$jscomp$optchain$tmp1103933637$0,eventInfo=eventInfo$jscomp$0,container=eventInfo.eic,actionMap=actionElement.__jsaction;if(!actionMap){var jsactionAttribute=module$contents$google3$javascript$jsaction$eventcontract_getAttr(actionElement,
"jsaction");if(jsactionAttribute){actionMap=module$contents$google3$javascript$jsaction$cache_parseCache[jsactionAttribute];if(!actionMap){actionMap={};for(var values=jsactionAttribute.split(module$contents$google3$javascript$jsaction$eventcontract_REGEXP_SEMICOLON),idx=0;idx<values.length;idx++){var value=values[idx];if(value){var colon=value.indexOf(":"),hasColon=-1!==colon;actionMap[hasColon?module$contents$google3$javascript$jsaction$eventcontract_stringTrim(value.substr(0,colon)):"click"]=hasColon?
module$contents$google3$javascript$jsaction$eventcontract_stringTrim(value.substr(colon+1)):value}}module$contents$google3$javascript$jsaction$cache_parseCache[jsactionAttribute]=actionMap}jsactionAttribute=actionMap;actionMap={};for(type in jsactionAttribute){values=actionMap;a:if(idx=jsactionAttribute[type],colon=actionElement,value=container,!(0<=idx.indexOf(".")))for(;colon;){hasColon=colon;var namespace=hasColon.__jsnamespace;void 0===namespace&&(namespace=module$contents$google3$javascript$jsaction$eventcontract_getAttr(hasColon,
"jsnamespace"),hasColon.__jsnamespace=namespace);if(hasColon=namespace){idx=hasColon+"."+idx;break a}if(colon===value)break;colon=colon.parentNode}values[type]=idx}actionElement.__jsaction=actionMap}else actionMap=module$contents$google3$javascript$jsaction$eventcontract_EMPTY_ACTION_MAP,actionElement.__jsaction=actionMap}eventInfo.action=actionMap[eventInfo.eventType]||"";eventInfo.action&&(eventInfo.actionElement=actionElement);if(eventInfo$jscomp$0.action)break;$jscomp$optchain$tmp1103933637$0.__owner?
$jscomp$optchain$tmp1103933637$0=$jscomp$optchain$tmp1103933637$0.__owner:(type=void 0,"#document-fragment"!==(null==(type=$jscomp$optchain$tmp1103933637$0.parentNode)?void 0:type.nodeName)?$jscomp$optchain$tmp1103933637$0=$jscomp$optchain$tmp1103933637$0.parentNode:(actionElement=type=void 0,$jscomp$optchain$tmp1103933637$0=null!=(actionElement=null==(type=$jscomp$optchain$tmp1103933637$0.parentNode)?void 0:type.host)?actionElement:null))}JSCompiler_StaticMethods_handleEventInfo$self.dispatcher&&
!eventInfo$jscomp$0.event.a11ysgd&&($jscomp$optchain$tmp1103933637$0={eventType:eventInfo$jscomp$0.eventType,event:eventInfo$jscomp$0.event,targetElement:eventInfo$jscomp$0.targetElement,eic:eventInfo$jscomp$0.eic,action:eventInfo$jscomp$0.action,actionElement:eventInfo$jscomp$0.actionElement,timeStamp:eventInfo$jscomp$0.timeStamp,eirp:eventInfo$jscomp$0.eirp,eiack:eventInfo$jscomp$0.eiack},"clickonly"===$jscomp$optchain$tmp1103933637$0.eventType&&($jscomp$optchain$tmp1103933637$0.eventType="click"),
JSCompiler_StaticMethods_handleEventInfo$self.dispatcher($jscomp$optchain$tmp1103933637$0,!0));if(eventInfo$jscomp$0.actionElement){$jscomp$optchain$tmp1103933637$0=!1;if("maybe_click"!==eventInfo$jscomp$0.eventType){if(!module$exports$google3$javascript$jsaction$event$isGecko||"INPUT"!==eventInfo$jscomp$0.targetElement.tagName&&"TEXTAREA"!==eventInfo$jscomp$0.targetElement.tagName||"focus"!==eventInfo$jscomp$0.eventType)type=eventInfo$jscomp$0.event,type.stopPropagation?type.stopPropagation():type.cancelBubble=
!0}else"maybe_click"===eventInfo$jscomp$0.eventType&&($jscomp$optchain$tmp1103933637$0=!0);JSCompiler_StaticMethods_handleEventInfo$self.dispatcher&&(!(type=eventInfo$jscomp$0.actionElement)||"A"!==type.tagName||"click"!==eventInfo$jscomp$0.eventType&&"clickmod"!==eventInfo$jscomp$0.eventType||(type=eventInfo$jscomp$0.event,type.preventDefault?type.preventDefault():type.returnValue=!1),(type=JSCompiler_StaticMethods_handleEventInfo$self.dispatcher(eventInfo$jscomp$0))&&allowRehandling?JSCompiler_StaticMethods_handleEventInfo(JSCompiler_StaticMethods_handleEventInfo$self,
type,!1):$jscomp$optchain$tmp1103933637$0&&(JSCompiler_StaticMethods_handleEventInfo$self=eventInfo$jscomp$0.event,JSCompiler_StaticMethods_handleEventInfo$self.stopPropagation?JSCompiler_StaticMethods_handleEventInfo$self.stopPropagation():JSCompiler_StaticMethods_handleEventInfo$self.cancelBubble=!0))}}
function JSCompiler_StaticMethods_addEvent(JSCompiler_StaticMethods_addEvent$self,eventType){if(!(eventType in JSCompiler_StaticMethods_addEvent$self.eventHandlers)&&"mouseenter"!==eventType&&"mouseleave"!==eventType&&"pointerenter"!==eventType&&"pointerleave"!==eventType){var eventHandler=function(eventType,event,container){JSCompiler_StaticMethods_addEvent$self.handleEvent(eventType,event,container)};JSCompiler_StaticMethods_addEvent$self.eventHandlers[eventType]=eventHandler;var browserEventType=
"mouseenter"===eventType?"mouseover":"mouseleave"===eventType?"mouseout":"pointerenter"===eventType?"pointerover":"pointerleave"===eventType?"pointerout":eventType;if(browserEventType!==eventType){var eventTypes=JSCompiler_StaticMethods_addEvent$self.browserEventTypeToExtraEventTypes[browserEventType]||[];eventTypes.push(eventType);JSCompiler_StaticMethods_addEvent$self.browserEventTypeToExtraEventTypes[browserEventType]=eventTypes}JSCompiler_StaticMethods_addEvent$self.containerManager.addEventListener(browserEventType,
function(element){return function(event){eventHandler(eventType,event,element)}})}}module$exports$google3$javascript$jsaction$eventcontract$EventContract.prototype.handler=function(eventType){return this.eventHandlers[eventType]};
module$exports$google3$javascript$jsaction$eventcontract$EventContract.prototype.ecrd=function(dispatcher){this.dispatcher=dispatcher;var $jscomp$optchain$tmp1103933637$3;if(null==($jscomp$optchain$tmp1103933637$3=this.queuedEventInfos)?0:$jscomp$optchain$tmp1103933637$3.length){for(dispatcher=0;dispatcher<this.queuedEventInfos.length;dispatcher++)JSCompiler_StaticMethods_handleEventInfo(this,this.queuedEventInfos[dispatcher]);this.queuedEventInfos=null}};
function module$contents$google3$javascript$jsaction$eventcontract_getAttr(element,attribute){var value=null;"getAttribute"in element&&(value=element.getAttribute(attribute));return value}function module$contents$google3$javascript$jsaction$eventcontract_stringTrim(str){return"function"===typeof String.prototype.trim?str.trim():str.replace(/^\s+/,"").replace(/\s+$/,"")};function object$jscomp$inline_127(container,appId,events){var eventContract=new module$exports$google3$javascript$jsaction$eventcontract$EventContract;window.__ngEventContracts__||(window.__ngEventContracts__={});window.__ngEventContracts__[appId]=eventContract;if(appId="undefined"!=typeof Symbol&&Symbol.iterator&&events[Symbol.iterator])events=appId.call(events);else if("number"==typeof events.length)events={next:$jscomp$arrayIteratorImpl(events)};else throw Error(String(events)+" is not an iterable or ArrayLike");
for(appId=events.next();!appId.done;appId=events.next())JSCompiler_StaticMethods_addEvent(eventContract,appId.value);a:{eventContract=eventContract.containerManager;for(events=0;events<eventContract.containers.length;events++)if(container===eventContract.containers[events].JSC$2220_element){container=eventContract.containers[events];break a}container=new module$exports$google3$javascript$jsaction$event_contract_container$EventContractContainer(container);for(events=0;events<eventContract.eventHandlerInstallers.length;events++)eventContract.eventHandlerInstallers[events](container);
eventContract.containers.push(container)}return container}var parts$jscomp$inline_130=["jsaction","registerEvents"],cur$jscomp$inline_131=goog$global;parts$jscomp$inline_130[0]in cur$jscomp$inline_131||"undefined"==typeof cur$jscomp$inline_131.execScript||cur$jscomp$inline_131.execScript("var "+parts$jscomp$inline_130[0]);
for(var part$jscomp$inline_132;parts$jscomp$inline_130.length&&(part$jscomp$inline_132=parts$jscomp$inline_130.shift());)parts$jscomp$inline_130.length||void 0===object$jscomp$inline_127?cur$jscomp$inline_131[part$jscomp$inline_132]&&cur$jscomp$inline_131[part$jscomp$inline_132]!==Object.prototype[part$jscomp$inline_132]?cur$jscomp$inline_131=cur$jscomp$inline_131[part$jscomp$inline_132]:cur$jscomp$inline_131=cur$jscomp$inline_131[part$jscomp$inline_132]={}:cur$jscomp$inline_131[part$jscomp$inline_132]=
object$jscomp$inline_127;
`;