#!/bin/sh
# commit-msg git hook, see https://typicode.github.io/husky/#/ for more on how husky works.
. "$(dirname $0)/_/husky.sh"

# Ahead of creating the commit, validate the commit message.
yarn -s ng-dev commit-message pre-commit-validate --file $1;
