#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Allow for the formatting command to fail without exiting the script.
set +e

yarn -s ng-dev format staged 2>/dev/null

if [ $? -ne 0 ]; then
  echo "WARNING: failed to run file formatting (ng-dev format staged)"
fi