#!/bin/sh
. "$(dirname $0)/_/husky.sh"

set +e

yarn -s ng-dev commit-message restore-commit-message-draft $1 $2 2>/dev/null
if [ $? -ne 0 ]; then
  echo "WARNING: failed to run prepare-commit-msg hook"
fi

exit 0;
