load("@npm//:defs.bzl", "npm_link_all_packages")
load("@rules_angular//src/architect:ng_config.bzl", "ng_config")

package(default_visibility = ["//vscode-ng-language-service/integration:__subpackages__"])

npm_link_all_packages(name = "node_modules")

ng_config(
    name = "ng_config",
)

filegroup(
    name = "project",
    srcs = [
        ":ng_config",
        "//vscode-ng-language-service/integration/project/app:srcs",
        "//vscode-ng-language-service/integration/project/libs/post",
        "//vscode-ng-language-service/integration/project/libs/post:srcs",
    ],
    visibility = ["//vscode-ng-language-service/integration:__subpackages__"],
)
