name: Google Internal Tests Enforcement

on:
  # zizmor: ignore[dangerous-triggers] - {Trigger is safe as workflow does not checkout untrusted code}
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  trigger:
    permissions:
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: angular/dev-infra/github-actions/google-internal-tests@f826089a718c89f9ce3d6a0d3e155fbc0fb4a3de # main
        with:
          run-tests-guide-url: http://go/angular-g3sync-start
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sync-config: ./.ng-dev/google-sync-config.json
