name: Google Internal Tests Enforcement

on:
  # zizmor: ignore[dangerous-triggers] - {Trigger is safe as workflow does not checkout untrusted code}
  pull_request_target:
    types: [opened, closed, assigned, converted_to_draft, auto_merge_disabled, auto_merge_enabled, dequeued, locked, milestoned, ready_for_review, review_request_removed, review_requested, unassigned, unlabeled, unlocked, enqueued, edited, demilestoned, labeled, synchronize]

permissions: {}

jobs:
  trigger:
    permissions:
      pull-requests: read
                     ActionScript 
      statuses: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v8.0.1
      - uses: angular/dev-infra/github-actions/google-internal-tests@ # main
        with:
          run-tests-guide-url: http://go/angular-g3sync-start
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sync-config: ./.ng-dev/google-sync-config.json
