name: Merge Ready

on: pull_request_target

# Declare default permissions as read only.
permissions: {}

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/unified-status-check@616a50d0b747031b7ea052733adf3771fa6cace9
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
