name: Merge Ready

on:
  # zizmor: ignore[dangerous-triggers] - {Trigger is safe as workflow does not checkout untrusted code}
  pull_request_target:

# Declare default permissions as read only.
permissions: {}

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/unified-status-check@630fa0aa7ce9b7127b1ec4464b6af02d34f8154b # main
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
