name: Merge Ready

on: pull_request_target

# Declare default permissions as read only.
permissions: {}

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/unified-status-check@e4dcda13e469f50a6bd92667e2ded8b98173bf2c
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
