i0.ɵɵelementStart(0, "div") // SOURCE: "/input_binding_class.ts" <div 
…
i0.ɵɵtext(1, "Message") // SOURCE: "/input_binding_class.ts" Message
…
i0.ɵɵelementEnd() // SOURCE: "/input_binding_class.ts" </div>
…
i0.ɵɵclassProp("initial", ctx.isInitial) // SOURCE: "/input_binding_class.ts" [class.initial]="isInitial"