.ɵɵelementStart(0, "div");\n     // SOURCE: "/ng_if_simple.ts" "<div *"
…
.ɵɵtext(1);\n     // SOURCE: "/ng_if_simple.ts" "{{ name }}"
…
// TODO: Work out how to fix the broken segment for the last item in a template
.ɵɵelem // SOURCE: "/ng_if_simple.ts" "</div>'"
…
.ɵɵtextInterpolate(ctx_r0.name);\n  }\n}\n\nexport class  // SOURCE: "/ng_if_simple.ts" "{{ name }}"
…
.ɵɵtemplate(0, TestCmp_div_0_Template, 2, 1, "div", 0) // SOURCE: "/ng_if_simple.ts" "<div *"
…
.ɵɵproperty("ngIf", ctx.showMessage()) // SOURCE: "/ng_if_simple.ts" "ngIf="showMessage()\">"
