i0.ɵɵelementStart(0, "button", 0) // SOURCE: "/output_binding_complex.ts" "<button "
…
ctx.items.push( // SOURCE: "/output_binding_complex.ts" "items.push("
…
"item" // SOURCE: "/output_binding_complex.ts" "'item'"
…
 + ctx.items.length) // SOURCE: "/output_binding_complex.ts" " + items.length)"
…
i0.ɵɵtext(1, "Add Item") // SOURCE: "/output_binding_complex.ts" "Add Item"
…
i0.ɵɵelementEnd() // SOURCE: "/output_binding_complex.ts" "</button>"
