…
i0.ɵɵelementStart(1, "input", 0) // SOURCE: "/two_way_binding_simple.ts" "<input "
…
// TODO: improve mappings here
i0.ɵɵtwoWayListener("ngModelChange", function TestCmp_Template_input_ngModelChange_1_listener($event) { i0.ɵɵtwoWayBindingSet(ctx.name, $event) || (ctx.name = $event); return $event; }) // SOURCE: "/two_way_binding_simple.ts" "[(ngModel)]=\"name\""
…
i0.ɵɵelementEnd() // SOURCE: "/two_way_binding_simple.ts" "<input "
